# Generated by Django 6.0.6 on 2026-06-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mahsulot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('release_year', models.IntegerField()),
                ('duration', models.CharField(max_length=50)),
                ('video', models.CharField(max_length=500)),
                ('genre', models.CharField(max_length=100)),
                ('rating', models.CharField(max_length=20)),
                ('company', models.CharField(max_length=255)),
                ('cast', models.TextField()),
            ],
        ),
    ]
