# Generated by Django 6.0.6 on 2026-06-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mahsulot',
            name='image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
