# Generated by Django 6.0.6 on 2026-06-18 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_mahsulot_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mahsulot',
            name='release_year',
            field=models.CharField(max_length=400),
        ),
    ]
